name: Bun CI

concurrency:
  group: bun-ci-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "*.md"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2.0.2
        with:
          bun-version: 1.2.2

      - name: Cache Bun modules
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('apps/web/bun.lockb') }}

      - name: Install dependencies
        working-directory: apps/web
        run: bun install

      - name: Build
        working-directory: apps/web
        run: bun run build

      - name: Run tests
        working-directory: apps/web
        run: echo "No tests implemented yet"
        continue-on-error: true
